# rm ex1.out intIndex.idx test.idx; g++ -Wall main.cpp -o ex1.out; ./ex1.out
test:
	rm a.out test.idx FreeTest.idx TreeTest.idx IntIndex.idx; g++ main.cpp; ./a.out; rm a.out test.idx FreeTest.idx IntIndex.idx TreeTest.idx